feat(YQL): improve suggestions calculation
gravity-ui/websql-autocomplete pull request #184
Opened 2024-05-28 13:57 UTC by Raubzeug

Closes #ISSUE_ID

2024-05-29 09:20 UTC, roberthovsepyan commented on src/autocomplete/databases/yql/yql-autocomplete.ts
> +type InternalSuggestions<T> = Omit<
nit: maybe easier to use ```Pick``` here instead of ```Omit```?

2024-05-29 09:20 UTC, roberthovsepyan commented on src/autocomplete/databases/yql/yql-autocomplete.ts
> +}
```statement```, we don’t use shortened names

2024-05-29 11:25 UTC, roberthovsepyan commented on src/autocomplete/databases/yql/yql-autocomplete.ts
> +    // -Infinity is a start point. When we enter a rule, where such kind of suggestion is possible, we mark it as "1", it's kinda initialisation. -Infinity is set to avoid cases when we reach ceil ("
```starting point```
```it's kind of initialisation```
```reach ceiling```
```without initialising the rule```

2024-05-29 11:41 UTC, roberthovsepyan approved these changes

2024-05-29 11:56 UTC, NikitaShkaruba approved these changes

2024-05-30 12:44 UTC, roberthovsepyan requested changes

2024-05-30 12:44 UTC, roberthovsepyan commented on src/autocomplete/databases/yql/helpers.ts
> +function checktRuleInListGetter(ruleList: c3.RuleList): {
I'd rename it to ```getRuleCheckHelpers```

2024-05-30 12:44 UTC, roberthovsepyan commented on src/autocomplete/databases/yql/helpers.ts
> +    const hasPreviousTokenUSER = Boolean(
```hasPreviousTokenUser``` for proper camel case
has to be changed everywhere

2024-05-30 12:44 UTC, roberthovsepyan commented on src/autocomplete/databases/yql/grammar/README.md
> +When new grammar is arrived, it is a must to do next steps before generating parsers:
Before generating parsers for new grammar version following steps should be done:

2024-05-30 12:44 UTC, roberthovsepyan commented on src/autocomplete/databases/yql/grammar/README.md
> +1. Add to the end of file next statements:
Put following statements at the end of the file

2024-05-30 15:16 UTC, roberthovsepyan approved these changes

2024-05-30 15:18 UTC, merged