feat(YQL): support variables and scopes
gravity-ui/websql-autocomplete pull request #258
Opened 2024-12-12 11:27 UTC by Raubzeug

2024-12-12 13:01 UTC, roberthovsepyan requested changes

2024-12-12 13:01 UTC, roberthovsepyan commented on src/autocomplete/shared/compute-token-position.ts
> +function positionOfToken(
this is not a proper function name
I suggest renaming this to `computeTokenPositionOfNode` or sth similar

2024-12-12 13:20 UTC, Raubzeug commented on src/autocomplete/databases/yql/yql-autocomplete.ts
> +        type: new (...args: any[]) => c3.ScopedSymbol,
made a few rounds - doesn't work with unknown. Will add an exception for this line.

2024-12-12 13:45 UTC, Raubzeug commented on src/autocomplete/shared/compute-token-position.ts
> +                tokens.get(i),
It seems it's ok: if the token position is found in cycle above, it will be returned. If not, here we are.

2024-12-12 13:46 UTC, Raubzeug commented on src/autocomplete/shared/compute-token-position.ts
> +                return pos;
We want to traverse through overall cycle. So we will return only if position is found.

2024-12-12 13:57 UTC, Raubzeug commented on src/autocomplete/shared/variables.ts
> +    const variables = suggestVariables(symbolTable, tokenPosion.context);
For now yes, but I'm going to use other parts of the interface in the near future!

2024-12-13 09:52 UTC, roberthovsepyan requested changes

2024-12-13 09:52 UTC, roberthovsepyan commented on src/autocomplete/databases/yql/yql-autocomplete.ts
> +    addVariableSymbol = (variableGetter: (index: number) => string | undefined): void => {
let's rename `variableGetter` to `getVariable`

2024-12-13 09:52 UTC, roberthovsepyan commented on src/autocomplete/databases/yql/yql-autocomplete.ts
> +            //this variable should be in global scope
please add a space after //

2024-12-13 09:52 UTC, roberthovsepyan commented on src/autocomplete/databases/yql/yql-autocomplete.ts
> +        //this variable should be in local scope, so it should be extracted inside withScope callback
please, add space after //

2024-12-13 09:52 UTC, roberthovsepyan commented on src/autocomplete/databases/yql/yql-autocomplete.ts
> +    protected defaultResult(): c3.SymbolTable {
let's add a newline here
we should separate all methods with newlines

2024-12-13 09:52 UTC, roberthovsepyan commented on src/autocomplete/databases/yql/yql-autocomplete.ts
> +        const callback = (): {} => {
let's give this function a proper name, like `addVariable` or sth

2024-12-13 09:52 UTC, roberthovsepyan commented on src/autocomplete/shared/compute-token-position.ts
> +    parseTree: ParseTree | null,
this is still unresolved

2024-12-13 09:52 UTC, roberthovsepyan commented on src/autocomplete/shared/compute-token-position.ts
> +    if (
I think you missed this?

2024-12-13 09:52 UTC, roberthovsepyan commented on src/autocomplete/shared/compute-token-position.ts
> +        if (tokenPosition !== undefined) {
we check here for undefined and lower we just check for falsy value
these checks should be the same
I suggest to just change this to `if (tokenPosition)`

2024-12-13 09:52 UTC, roberthovsepyan commented on src/autocomplete/shared/variables.ts
> +export function getVariablesSuggestions<L extends LexerType, P extends ParserType>(
let's rename this to `getVariableSuggestions`
double pluralization doesn't read well

2024-12-13 09:52 UTC, roberthovsepyan commented on src/autocomplete/shared/variables.ts
> +    const symbolTable = symbolVariableVisitor.symbolTable;
nit: we don't really need this variable, we can just pass `symbolVariableVisitor.symbolTable` directly to `suggestVariablesFunction`

2024-12-13 09:52 UTC, roberthovsepyan commented on src/autocomplete/shared/variables.ts
> +    const variables = suggestVariables(symbolTable, tokenPosition.context);
nit: here as well we don't really need this variable, we can just return this

2024-12-13 09:52 UTC, roberthovsepyan commented on src/autocomplete/shared/variables.ts
> +    //Local scope
please add spaces in all comments after //

2024-12-13 09:52 UTC, roberthovsepyan commented on src/autocomplete/shared/compute-token-position.ts
> +type TokenPosition = {index: number; context: ParseTree; text: string};
this interface doesn't look like `TokenPosition` to me
I think position is only a small part of it, maybe we can rename it to something more appropriate?
what about `TokenContext`? or even `CursorContext`?

2024-12-13 09:59 UTC, Raubzeug commented on src/autocomplete/shared/compute-token-position.ts
> +    if (
It seems if I try to add guard, it's clause will be huge and complicated, so I decided to stick to present realisation.

2024-12-13 12:08 UTC, roberthovsepyan requested changes

2024-12-13 12:08 UTC, roberthovsepyan commented on src/autocomplete/shared/compute-token-position.ts
> +    if (!parseTree) {
we don't need this check now

2024-12-13 12:08 UTC, roberthovsepyan commented on src/autocomplete/shared/compute-token-position.ts
> +    //it means token is eof
please add space after //

2024-12-13 12:08 UTC, roberthovsepyan commented on src/autocomplete/shared/variables.ts
> +        //Global scope
please add a space after //

2024-12-13 12:08 UTC, roberthovsepyan commented on src/autocomplete/shared/variables.ts
> +            //if symbol's parent has context it means it is local scoped, so no need to suggest it in global scope
please add a space after //

2024-12-13 12:08 UTC, roberthovsepyan commented on src/autocomplete/shared/variables.ts
> +            //if symbol's parent has context it means it is local scoped, so no need to suggest it in global scope
also we should keep each comments to one style
so they should all start will capital letters
please fix everywhere

2024-12-13 12:08 UTC, roberthovsepyan commented on src/autocomplete/shared/compute-token-position.ts
> +export function computeTokenPosition(
we should change all function and variable names to tokenContext then

2024-12-13 12:08 UTC, roberthovsepyan commented on src/autocomplete/shared/variables.ts
> +    const tokenPosition = computeTokenPosition(parseTree, tokenStream, cursor);
here too

2024-12-13 12:21 UTC, roberthovsepyan approved these changes

2024-12-13 12:23 UTC, merged