refactor: replace delete statement json-test with jest-test in general parser
gravity-ui/websql-autocomplete pull request #91
Opened 2023-11-28 16:04 UTC by NikitaShkaruba

part of #85

2023-11-28 20:09 UTC, roberthovsepyan commented on src/parsing/parsers/generic/jison/delete/delete.test.ts
> +describe('delete statement', () => {
are we sure we want a global describe here? doesn't really add much value and makes code less readable due to nesting

2023-11-28 20:09 UTC, roberthovsepyan commented on src/parsing/parsers/generic/jison/delete/delete.test.ts
> +})
Looks good to me, pretty simple

2023-11-29 08:48 UTC, viladimiru requested changes

2023-11-29 08:48 UTC, viladimiru commented on src/parsing/parsers/generic/jison/delete/delete.test.ts
> +        expect(parseGenericSql('DELETE FROM test_table ', '').suggestKeywords)
I'm scared that we didn't check whole result as we did it in `test.json`, imo its reducing significance of tests

2023-11-29 11:42 UTC, roberthovsepyan approved these changes

2023-11-29 11:43 UTC, viladimiru approved these changes

2023-11-29 11:43 UTC, merged